spring.application.name=FitLife

# where course image will be saved
fitlife.upload.image-dir=D:/Project/Personal Project/FitLife/src/main/resources/static/Image

# where video files will be saved
file.upload-videos-dir=D:/Project/Personal Project/FitLife/src/main/resources/static/Videos

# URL prefix used when building video access urls
file.video-url-prefix=/api/accessVideo/

#jpa hibernate property
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#multipart property
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=300GB
spring.servlet.multipart.file-size-threshold=1KB
spring.servlet.multipart.max-request-size=200GB

#db setup
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT secret key
jwt.secret=${JWT_SECRET}

#mail setup
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}

#razorpay property
razorpay.key=${RAZORPAY_KEY}
razorpay.secret=${RAZORPAY_SECRET}
tLN54VVr7NHeZtnfRSQfAYLJ